### ISSUE TITLE
standalone usage: missing [classes in] light-psi-all.jar 

### ISSUE THREAD

**Issue by eprst** [JetBrains/Grammar-Kit#117]
`light-psi-all.jar` is missing from the latest releases. I tried to build it as indicated in the instruction, but resulting jar is missing a few things:
```
com.intellij.lang.ParserDefinition$SpaceRequirements
com.intellij.lang.parser.GeneratedParserUtilBase*
```
and if stubs are used:
```
com.intellij.psi.stubs.StubInputStream
com.intellij.psi.stubs.StubOutputStream
com.intellij.psi.stubs.IndexSink
com.intellij.psi.stubs.StubBase
com.intellij.psi.stubs.ObjectStubBase
com.intellij.extapi.psi.StubBasedPsiElementBase
com.intellij.extapi.psi.StubBasedPsiElementBase$1
```

**Comment by gregsh** [comment]
@eprst

You can pack classes required for any work by recording them via `-verbose:gc` java option.
To pack files run `java -cp grammar-kit.jar org.intellij.grammar.LightPsi <out-dir> <classes.log.txt>`
With the resulting jar one should be able to safely do no more than what you did while recording.

I publish light-psi-all.jar produced by `LightPsi-All: package` run configuration (which depends on some grammars generation) because some people wanted to generate grammars via CLI during build process.
The specified classes are not required for Grammar-Kit generator, so they are surely missing.
