### ISSUE TITLE
Easy API for stand alone Java parsing

### ISSUE THREAD

**Issue by bootstraponline** [JetBrains/Grammar-Kit#151]
I modified [LightPsi](https://github.com/JetBrains/Grammar-Kit/blob/master/src/org/intellij/grammar/LightPsi.java) and was able to parse a local Java file into `PsiJavaFile` and extract some `PsiElement`s.

Any thoughts on improving the API so parsing Java doesn't require 100+ LoC of registration calls?

**Comment by gregsh** [comment]
And here they are, my thoughts:

1. Considering the IntelliJ IoC container approach, the only way to do that is to shove that 100+ lines under the carpet, e.g. some util class (LightPsi approach), or xml. The main problem is that over time it will break due to some new extension point or service. So either it is managed by IntelliJ team or it breaks from time to time.

2. Considering the amount of code in JetBrains/community repository and the main goal of the team, which is to provide the best IDE-experience, I don't think any work to reduce the clutter is going to happen any time soon.

**Comment by bootstraponline** [comment]
Ok, good to know. I will maintain my own helper class then.

**Comment by bootstraponline** [comment]
After two days the parser is able to handle classes & fails on methods.

- https://gist.github.com/bootstraponline/cea794f86b0b4cc5dfee15c150cf5d8c

It's disappointing that the API can't parse Java code. If there are other projects you know of that would work for this use case, that'd be helpful. I found [javaparser](https://github.com/javaparser/javaparser) which I'll look into next.
