### ISSUE TITLE
Alert user of methods not detected in ImplUtil class?

### ISSUE THREAD

**Issue by rhencke** [JetBrains/Grammar-Kit#155]
Consider the code from the Sample.bnf file in https://github.com/JetBrains/intellij-sdk-docs/blob/master/code_samples/simple_language_plugin/src/com/simpleplugin/Simple.bnf
```
psiImplUtilClass="com.simpleplugin.psi.impl.SimplePsiImplUtil"
/* <snip> */
property ::= (KEY SEPARATOR VALUE?)|KEY {
/* <snip> */
    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
```

If ```SimplePsiImplUtil``` contains the method ```getName```, but is missing the method ```setName``` (or, say, if ```setName``` has the wrong signature), then the end result is that ```PropertyImpl``` will be generated with only ```getName```:

```java
  @NotNull
  public String getName() {
    return SimplePsiImplUtil.getName(this);
  }
```

However, there are no errors or warnings or notes about ```setName``` not being generated (that I could find), or why it was not generated.  As a beginner, at least, this was very difficult for me to track down.

At the very least, for cases like this, could a note be placed in the generated source code to this effect?  Something like:

```java
  @NotNull
  public String getName() {
    return SimplePsiImplUtil.getName(this);
  }

  // NOTE: setName was not generated, because no function matching the following
  // signature was found in class 'com.simpleplugin.psi.impl.SimplePsiImplUtil':
  // public static PsiElement setName(SimpleProperty element, String newName)
```

**Comment by rhencke** [comment]
@gregsh Thanks for doing this!

**Comment by calexHG** [comment]
Oh well-meaning Mr. Robert Hencke, you, you just had to leave a "in the
worst case you could settle for just doing <such and such>"-option, didn't
you? ;)


With just a comment in one of a project's 80 never-read, generated
interface files, errors will go on unnoticed, just as before.. D'oh..

On Apr 25, 2017 12:04 AM, "Robert Hencke" <notifications@github.com> wrote:

@gregsh <https://github.com/gregsh> Thanks for doing this!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JetBrains/Grammar-Kit/issues/155#issuecomment-296895592>,
or mute the thread
