### ISSUE TITLE
Limiting expression type when using left-recursion

### ISSUE THREAD

**Issue by ice1000** [JetBrains/Grammar-Kit#174]
As described in #95 , we can only use left-recur under a very limited circumstance, like

```bnf
extends ("*.Expr")=expr

expr ::= assign | op | primary
private assign ::= assignExpr
private op ::= opExpr
private primary ::= primaryExpr
assignExpr ::= expr '=' expr
opExpr ::= expr '+' expr
primaryExpr ::= number | symbol
number ::= <A token>
symbol ::= <Another token>
```

And I want to limit the left value of `assignExpr` to `symbol` rather than `expr`, is there any approaches that allow me to do that?  
I tried changing `assignExpr` to `symbol '=' expr` but it says I employed unsupported left-recursion type.

Is it so difficult to provide full support for left recursion? :thinking:

**Comment by gregsh** [comment]
Yes, but there're some tricks:

1. `assignExpr ::= expr '=' symbol`  
  That will limit the second argument by priority, so it won't work for atoms and prefix expressions,
  but for binary, n-ary and postfix it's OK. Meaning that `E = number` will be accepted too.
   `assignExpr ::= expr '=' &symbol symbol`  fixes that, because the operator checks for the next token
   
2. `assignExpr ::= expr ('=' symbol)`
  That will make a postfix expression instead of a binary expression

Different approaches have different implications desired and not.
