### ISSUE TITLE
Pinned rule fails, but no error reported

### ISSUE THREAD

**Issue by klazuka** [JetBrains/Grammar-Kit#176]
Using the following BNF, I would expect that given an input `foo bogus end`, the "bogus" token in the input would be marked as an error and the `foo` node would be "successfully" parsed (although partial).
```
{
  tokens=[
    space='regexp:\s+'
    id='regexp:\p{Alpha}\w*'
  ]
}

root ::= foo 'end'
foo ::= 'foo' 'bar' {pin=1}
```

But instead no error is marked and the Foo node is not even constructed, as shown:
<img width="474" alt="gk_bad_no_error_shown" src="https://user-images.githubusercontent.com/84525/37880072-d27df810-3037-11e8-9adf-90abc9f1a987.png">

If I remove the pinning, then the error is marked correctly:
<img width="483" alt="gk_good_without_pin" src="https://user-images.githubusercontent.com/84525/37880081-e1b0775e-3037-11e8-99ab-0d0a3e534036.png">

I might be totally wrong about pinning, but my understanding is that it should:

- never suppress the reporting of an error in the parse tree
- should allow a node to be partially constructed assuming that the pinned prefix matched

**Comment by jvolkman** [comment]
Could be buggy behavior with the root node which is handled a bit differently - at least in the generated parser. If you insert another node under root it works as you expect:

```
{
  tokens=[
    space='regexp:\s+'
    id='regexp:\p{Alpha}\w*'
  ]
}

root ::= sub
sub ::= foo 'end'
foo ::= 'foo' 'bar' {pin=1}

```
But the real problem is that your grammar is lacking recovery. Usually when using `pin` you'll also specify  `recoverWhile` to tell the parser what to do with bad input after the pinned match. This is easy in languages that end with semicolons or similar. For example:

```
root ::= statement*
statement ::= (foobar) ';'
private statement_recovery ::= !(';')  // consume all non-semicolon tokens

foobar ::= 'foo' 'bar' {
  pin = 1
  recoverWhile = statement_recovery
}
```

Given the input `foo bar; foo bogus; foo bar;`, you'll see a PSI tree with 3 `STATEMENT` nodes, with the second one containing an embedded PsiError element indicating the bad 'bogus' token. Without specifying recoverWhile, the same input would give you one `STATEMENT` node and then a bunch of unrecognized tokens. The third, valid statement would not be parsed. The problem is that the parser fails to parse the `FOOBAR` rule upon encountering 'bogus' and then does not know how to proceed. Without recovery, it does not know where to start parsing again.

Specifying a recoverWhile with your original example generates an error given your original bad input:

```
root ::= foo 'end'
foo ::= 'foo' 'bar' {
  pin=1
  recoverWhile = foo_recover
}
private foo_recover ::= !'end'
```

**Comment by klazuka** [comment]
Thanks for the detailed response. I intentionally left out `recoverWhile` in this example to keep it as simple as possible since the absence of recovery should not change the fact that an error was encountered (and should be reported).
