### ISSUE TITLE
Order of tokens (match subsets) in BNF

### ISSUE THREAD

**Issue by leus** [JetBrains/Grammar-Kit#181]
Hello,

I need to match two different sets of tokens, one which is a subset of the other.
```
{
 tokens = [
  space    = 'regexp:\s+'
  id     = 'regexp:\w+'
  value = 'regexp:[A-Za-z-_]+'
 ]
}
expr ::= id space value
```
If I enter the following in Live Preview, I get `value expected, got 'two'`:
```
one two
```
What is the proper way to specify a set of characters that is more specific than the other? I tried changing the order in the tokens list, but the error just changed to `id expected, got 'one'`.

## Bigger picture

The problem I describe is just one of the many stumbling blocks I'm having trying to write my parser. I'm just beginning to use Grammar-Kit.

My goal is to parse a custom template format which is formed with textual separators and some incomplete XML fragments between them, so I need to differentiate characters allowed in tag names, inside XML comments, and so on. I don't think I can use an XML parser because I have starting tags with no end tags between sections of my file. 

My goal for this project is to parse our vast existing template library and move it to MPS. My files look something like this, and I'm having a hard time creating the BNF.

```
*******SectionA
<Intro>
<PropertyA>Value of property A</PropertyA>
<PropertyB>Value of property B</PropertyB>
<PropertyC>Value of property C with some [VARIABLE]</PropertyC>
</Intro>
*******SectionB
Var_[VARIABLE]=some text or even [VARIABLE2]
Var_[VARIABLE2]=another variable
*******SectionC

<!--Valid XML spaces and comments -->
<Job>
<Info>
<Name>Bobby</Name>
<Priority>High</Priority>
</Info>
<Body>

*******SectionD
<RepeatingBlock id="1" desc="Some [DESCRIPTION]">
<Work>
<Value attr="a">some value</Value>
<AnotherValue><Something data="some data [VARIABLE]">something [VARIABLE2]</Something>
</Work>
</RepeatingBlock>

*******SectionE
</Body>
</Job>
```

**Comment by gregsh** [comment]
Here's my "proper" way:

IDE support has several levels, the rule of thumb is to make each level as simple as possible.

1. Lexer
2. Parser
3a. Annotations (quick in-editor mode; slow/batch mode via Annotator Inspection)
3b. Inspections (quick in-editor mode; slow/batch mode)

Forget about Live Preview and "regex" tokens, they are just for fun and quick-and-dirty startup. Go for real/production JFlex lexer. Tweak flex file logic as you like using non-returning rules and lexer states, so to distinguish as much tokens as possible, so that parser can always build some good AST.

IDE-grade parser shall build AST even for not-very-correct cases, so that completion and other IDE logic have something to work with. Push all non-trivial validation logic up to Inspections.

So choices are:
1. use different tokens using flex logic (e.g. "id" after new line, or before "=", otherwise a "value")
2. use one token and add an inspection that highlights "bad" ids or values.

**Comment by leus** [comment]
So, I guess my question is: is it not possible to distinguish between two token types if they are ambiguous in the token list?

**Comment by gregsh** [comment]
Order of tokens does matter:
```
// Live preview for: 12 aaa bbb
// Shows: AAA: '12' AAA: 'aaa' AAA: 'bbb'
{ tokens=[
AAA="regexp:\w+"
BBB="regexp:[a-f]+"
WS="regexp:\s+"
] }
rule ::= (AAA | BBB) +
```

```
// Live preview for: 12 aaa bbb
// Shows: AAA: '12' BBB: 'aaa' BBB: 'bbb'
{ tokens=[
AAA="regexp:\w+"
BBB="regexp:[a-f]+"
WS="regexp:\s+"
] }
rule ::= (AAA | BBB) +
```

**Comment by leus** [comment]
I gather that the second example should have 'BBB' before 'AAA'. That makes sense.
But my problem is similar to the following:

```bnf
// Live preview for: 12 aaa bbb
// Shows: AAA: '12' PsiErrorElement: BBB expected, got 'aaa' AAA: 'bbb'

{ tokens=[
AAA="regexp:\w+"
BBB="regexp:[a-f]+"
WS="regexp:\s+"] }
rule ::= AAA BBB AAA
```

```bnf
// Live preview for: 12 aaa bbb
// Shows: AAA: '12' BBB: 'aaa' PsiErrorElement: AAA expected, got 'bbb'
{ tokens=[
BBB="regexp:[a-f]+"
AAA="regexp:\w+"
WS="regexp:\s+"] }
rule ::= AAA BBB AAA
```

I understand tokens are very basic and will match as soon as possible. Is there a way to define a set of valid characters in a _rule_ instead of a token?

On the same vein, is it possible to express the following rule? ("except"):
```bnf
SomeRule ::= (Char - '-')
```

**Comment by gregsh** [comment]
It is possible to do the following (negative lookahead predicate with text matched prefix)
```
SomeRule ::= !'-' Char
```
