### ISSUE TITLE
What is the correct way to write a .bnf file 

### ISSUE THREAD

**Issue by oldhiccup** [JetBrains/Grammar-Kit#259]
I am really frustrated and I did a lot to ask the question, I read and re-read the documentation, I looked for non-internal examples and I really couldn't understand how the bnf syntax works.

I tried some alternatives after reading in some places here and there which is a simple syntax, but the learning curve is not too short

A whole day and I managed to produce little.

The rules I want to implement are simple, something like

.bnf
```
LABEL ::= 'label' SEPARATOR CRLF? TAB  countless(KEY? WHITEPACE STRING? CRLF?) TAB 'return'
```
result expected

```

label:

    key "value"
    
    key "value"
    
    key "value"
    
    key "value"
    
    return
```
or 
.bnf
```
DEFINE ::= 'define' KEY SEPARATOR Class(KEY?=VALUE?,KEY?=VALUE?...)
```

result expected
```
define key  = OneClass(att="value", att2=10)

```

**Comment by JojOatXGME** [comment]
Ignoring the spaces, I guess the Grammar for your first example would look something like this.

    label ::= 'label' ':' label_entry* 'return'
    label_entry ::= key string

I think you should usually ignore spaces in your Grammar. By returning your whitespace tokens from `ParserDefinition.getWhitespaceTokens`, these tokens will not be provided to the parser. However, it looks like your language is aware of spaces (similar to *Python*). Did you look for an example of such a language?

**Comment by oldhiccup** [comment]
> 
> 
> Ignoring the spaces, I guess the Grammar for your first example would look something like this.
> 
> ```
> label ::= 'label' ':' label_entry* 'return'
> label_entry ::= key string
> ```
> 
> I think you should usually ignore spaces in your Grammar. By returning your whitespace tokens from `ParserDefinition.getWhitespaceTokens`, these tokens will not be provided to the parser. However, it looks like your language is aware of spaces (similar to _Python_). Did you look for an example of such a language?

It is a python-based SDK (Ren'py), I really don't think I know how to search

I found a complete Python example https://inst.eecs.berkeley.edu/~cs164/fa11/python-grammar.html

I will study for him, thanks anyway for the help.

**Comment by JojOatXGME** [comment]
In your example, they describe that the lexer injects a special `INDENT` or `DEDENT` token when the indentation level changes. See points (6) and (7) in *Lexical Structure* of the example you have mentioned.

They also note that the parser emits significant `NEWLINE` tokens when outside of strings and braces. See point (4). To replicate this in Grammar Kit, you need a special newline token which is NOT part of `ParserDefinition.getWhitespaceTokens`. However, your lexer must not emit this token inside of braces (or if any of the other exceptions apply). In such cases, your lexer should emit `TokenType.WHITE_SPACE` (which should be returned by `ParserDefinition.getWhitespaceTokens`) so your parser doesn't see it.

I hope that helps. Since your example you have mentioned above is more general, maybe it would help to find an example specifically for *Grammar-Kit*? Maybe you can find an example of such a Grammar in the [IntelliJ Platform Explorer](https://plugins.jetbrains.com/intellij-platform-explorer/?extensions=com.intellij.lang.parserDefinition).

Also note that I am also just a random user of Grammar-Kit who tries to help. You do not have to close the issue if my answer dos not help.

**Comment by oldhiccup** [comment]
@JojOatXGME Thanks again for trying to help, I'm already a bit tired of trying to ask for help from those responsible for open source libraries, they usually don't dedicate themselves, as you did now, to try to answer users' doubts.

I will continue studying to see if I can get out of the place.

Thank you one more time.
