### ISSUE TITLE
Support Kotlin classes/objects as `psiImplUtilClass`

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/Grammar-Kit#70]
For now, `psiImplUtilClass` can be only java class, and it prevents writing kotlin-only plugins.

**Comment by gregsh** [comment]
How can that be done?
Please see [JavaHelper.java](https://github.com/JetBrains/Grammar-Kit/blob/master/support/org/intellij/grammar/java/JavaHelper.java)

**Comment by gregsh** [comment]
I'll switch GK to UAST when it is ready.

**Comment by calexHG** [comment]
Cheers @VladRassokhin .

I just started using the `psiImplUtilClass` option today, but so far I've had no issues using Kotlin with it. Check out a sample implementation below..

```
// Class names redacted for witness protection purposes

class
XyzPsiImplUtil
{
    companion object
    {
        @JvmStatic @Override fun
        getDeclDefList( declDefsVariant: XyzModuleDeclDefs_Impl ): List<XyzDeclDef>
        {
            return declDefsVariant.moduleDeclDefsDeclDefList.map {
                it.declDef
            }.filterNotNull()
        }

        @JvmStatic @Override fun
        getDeclDefList( declDefsVariant: XyzRecoverableDeclDefsP_Impl ): List<XyzDeclDef>
        {
            return declDefsVariant.recoverableDeclDefsDeclDefPRList.map {
                it.declDef
            }.filterNotNull()
        }
    }
}
```

GK is expecting static methods, which isn't the approach that Kotlin uses in the JVM by default. With the syntax used above (minus my overly-long rule names), however, the methods will be found by GK and you should hopefully have no problems.

Also, it's highly probable that the Kotlin situation has simply evolved in the 1 year since your posting.

**Comment by calexHG** [comment]
And for the record, I don't normally reply to random 1-year old posts ;]

but it seemed Gregory was under the impression that it really wasn't working still, so I thought I should say something :P

**Comment by VladRassokhin** [comment]
Thanks for the info, @calexHG.
Seems `@JvmStatic` would solve problem, will try.

**Comment by calexHG** [comment]
Cool.

**Comment by calexHG** [comment]
So far, I've found that there have only been two persistent things keeping me from using Kotlin in some places.

1. Kotlin disallows using blanket `import foo.*` import statements when foo is a class (with the exception that it allows it when foo is a [legacy] Java class) {I might not recall the details correctly-- It was a while ago that I faced that and worked around it}. So, for convenience, I write my IElementType holder class in Java, to permit the blanket importing of its held token type constants.

2. Ironically, because Kotlin seems to have been primarily targeted at solving the woes of those locked into Java 6-level compatibility by Android, it actually ends up handicapping itself by not supporting the representation of interfaces with fully defined methods in them as being actual interfaces when compiled to the JVM. Instead, although it lets you use the interface keyword when defining such classes, it really just ends up representing them as abstract classes in the JVM. Basically, if you're using Java 8, it doesn't yet have a way for you to tell it it's okay to use Java 8 features, so you're stuck with the traditional, lousy Java single inheritance paradigm.

So, unfortunately, so far, I've been sometimes resorting to using Java classes for PSI super-classes (using a Kotlin-written psiImplUtilClass might decrease the number of times you'll have want to do this, though-- part of the reason I tried using it today).

**Comment by gregsh** [comment]
See [intellij-rust doing kotling](https://github.com/intellij-rust/intellij-rust/blob/master/src/main/kotlin/org/rust/lang/core/grammar/rust.bnf) with GK.

**Comment by calexHG** [comment]
::nods:: I've seen that one before. I just now noticed two things I hadn't before, though.

As a workaround for the second issue I mentioned, they manage to keep the class as a plain Java 6 interface by only adding function definitions to it via Kotlin extension functions. It seems that Kotlin must just keep extension functions as static functions in the JVM and just interprets them specially when your compiling Kotlin code. 

I'm not sure that approach would have worked for the use cases I had before (I'll have to check), but it's definitely a good trick to keep in mind. 
Thanks for the reminder.

**Comment by matklad** [comment]
@calexHG yeah, we don't use `psiImplUtil` at all. Most of the additional functions don't need to be dynamically dispatched, so extension methods work perfectly. And for those functions that must be virtual we add interfaces which are implemented by `ImplMixin` classes.

**Comment by ice1000** [comment]
This is meaningless.

Why don't you learn a bit more Kotlin?

```kotlin
@file:JvmName("JuliaPsiImplUtils")
package org.ice1000.julia.lang.psi.impl

import com.intellij.psi.PsiElement
import com.intellij.psi.ResolveState
import com.intellij.psi.scope.PsiScopeProcessor

fun MyExpr.processDeclTrivial(
		processor: PsiScopeProcessor,
		substitutor: ResolveState,
		lastParent: PsiElement?,
		place: PsiElement): Boolean {
	var run: PsiElement? = lastParent?.prevSibling ?: lastChild
	while (run != null) {
		if (!run.processDeclarations(processor, substitutor, null, place)) return false
		run = run.prevSibling
	}
	return true
}
```

And in bnf

```bnf
expr :: xxx {
  methods=[processDeclTrivial]
}
```

**Comment by ice1000** [comment]
I think my solution is the best answer to this issue, it works the same as Java, and it's even more elegant.

**Comment by VladRassokhin** [comment]
>This is meaningless.
>Why don't you learn a bit more Kotlin?

Why don't you learn a bit more Kotlin history?
Don't be ignorant and just look when issue was created, there was no `@JvmStatic` nor `@file:JvmName` those days (Kotlin 0.12). Though there was some poor man's `@platformStatic` which lived not sure for how long.
Nowadays it's of course quite easier to came up with some solution. However turns out those mixed Java-Kotlin psiImplUtilClass code is "write^W hack once - forget about it".


### Summary
To sum app all comments there're three proposed solutions (given Kotlin 1.0 or newer is used):
1. Just use extension functions, without `psiImplUtilClass`. Pro: simple, Con: poor interop with Java.
2. Mark all extension or simple functions with `@JvmStatic` and pass containing class as `psiImplUtilClass`. Pro: interop with Java, Con: should be added to each function.
3. Write extension functions in class and add `@file:JvmName` annotation, use those classname in `psiImplUtilClass`. Pro: interop with Java, Con: none? (ToBeTested).
Closing issue.

PS: Turns out decision to write plugin as much as possible in Kotlin was bad idea, considering compilation time and weird nullability-related compilation errors on IntelliJ version change. However in last two years first problem was kinda solved.
