### ISSUE TITLE
Add ability to control annotations in generated PSI classes when we use {elementType=...}

### ISSUE THREAD

**Issue by MichaelShumenko** [JetBrains/Grammar-Kit#76]
Thaks for great job.

Look example at [HOWTO.md#Compact expression parsing with priorities](https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#24-compact-expression-parsing-with-priorities)

```
expr ::= assign_expr
 .
 .
  | ref_expr
 .

simple_ref_expr ::= identifier {elementType=ref_expr}  // let qualified and simple references have the same type

ref_expr ::= expr '.' identifier
```
Method getExpr will be marked with annotation @NotNull. We would like to mark it like as @Nullable because <b>'simple_ref_expr' never containt 'expr' in self.</b>

![1](https://cloud.githubusercontent.com/assets/4786289/9340056/5ec7beb6-45f6-11e5-8868-fd0e91fda826.png)

![2](https://cloud.githubusercontent.com/assets/4786289/9340059/63ece164-45f6-11e5-8717-9d99ca8356e6.png)

Regards,
Michael

**Comment by gregsh** [comment]
That was way too long ago but.. on a second look it appeared to be a bug!

Here's the way to fix it:
{code}
// replace rename ref_expr to qualified_ref_expr
...
ref_expr ::= expr? '.' identifier
simple_ref_expr ::= identifier {extends=ref_expr elementType=ref_expr}
qualified_ref_expr ::= expr '.' identifier {extends=ref_expr elementType=ref_expr}
...
{code}

I've updated the HOWTO.md and full working sample in testData/generator/ExprParser.bnf.

I'm going to update generator so that ref_expr can be made 'fake' (no parsing method).
