### ISSUE TITLE
Bison features & precedence capability

### ISSUE THREAD

**Issue by andylamp** [JetBrains/Grammar-Kit#78]
I am trying to write a grammar using grammar-kit but your documentation is very *very* poor and it makes it hard to do (although live view helps). 

Now is there anything similar in Grammar-Kit to the %precedence, %left, %expect and other notation like functionality in Bison (or any way to emulate it).

PS: it would *really* help if there was a manual or a feature list that Grammat-Kit supports when coming from Bison as well as some equivalents examples.

**Comment by gregsh** [comment]
The underlying generator technologies are way too different.

[Bison](https://www.gnu.org/software/bison/): LR or GLR with LALR(1) tables
Grammar-Kit: [PEG](https://en.wikipedia.org/wiki/Parsing_expression_grammar) (human readable recursive descent) and [Pratt expression parsing](https://en.wikipedia.org/wiki/Pratt_parser)

Grammar-Kit also almost lacks real lexer specification because IntelliJ platform already uses [JFlex](http://jflex.de/) for that.

%precedence
Also see [HOWTO](https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md) for expression parsing with precedence.

 %left and %right
Expression parsing supports "rightAssociative" attribute.

%expect
PEG deals with conflicts by means of ordered-choice and predicates.
