### ISSUE TITLE
JFlex-1.4.x is ancient

### ISSUE THREAD

**Issue by Lucretia** [JetBrains/Grammar-Kit#89]
Don't you think it's time to update to 1.6?

**Comment by hurricup** [comment]
You may also comment here: https://youtrack.jetbrains.com/issue/IDEA-143060

**Comment by jvolkman** [comment]
The version of JFlex that JetBrains uses is patched to generate lexers that use CharSequence objects rather than char arrays, so a simple upgrade wouldn't be straight forward. There's a related JFlex issue at https://github.com/jflex-de/jflex/issues/153 to tweak the lexer interface such that non-char-arrays could be used.

**Comment by gregsh** [comment]
transition complete
