### ISSUE TITLE
EBNF support.

### ISSUE THREAD

**Issue by intersides** [JetBrains/Grammar-Kit#90]
Is there any plan to support EBNF ?

**Comment by gregsh** [comment]
Please explain.

**Comment by khronnuz** [comment]
I can't answer for the OP, but here goes my answer to this:

EBNF is a more expressive language than BNF. I would like to be able to create lexers/parsers entirely from (E)BNF definitions, even if that if does not have optimal performance. 

I subscribed to this issue because that was what I wanted. Now after playing with BNF support for a few weeks, I could settle for more documentation of what is supported, meaning BNF only examples :/.

**Comment by gregsh** [comment]
[Quick Grammar-Kit BNF overview](https://github.com/JetBrains/Grammar-Kit#quick-documentation).
